using UmbrellaFrame.ModelSync.Core;

namespace UmbrellaFrame.ModelSync.Oracle
{
    public class OracleColumnPrimaryKeyAttribute : DbColumnPrimaryKeyAttribute
    {
        public new bool IsAutoIncrement { get; }

        public OracleColumnPrimaryKeyAttribute(bool isIdentity = false) : base(isIdentity)
        {
            IsAutoIncrement = isIdentity;
        }

        public override string GetSqlSnippet()
            => IsAutoIncrement
                ? "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                : "PRIMARY KEY";
    }
}
