using Oracle.ManagedDataAccess.Client;
using UmbrellaFrame.ModelSync.Core;
using UmbrellaFrame.ModelSync.Oracle;

namespace UmbrellaFrame.ModelSync.OracleTest;

public sealed class OracleTableGeneratorTests
{
    private const string TableName = "MS_ORACLE_PRODUCTS";
    private static readonly string ConnectionString =
        Environment.GetEnvironmentVariable("MODELSYNC_ORACLE_CONNECTION")
        ?? "User Id=MODELSYNC_TEST;Password=ModelSync_Pass123;Data Source=127.0.0.1:11521/FREEPDB1";

    [Test]
    public void GenerateOracleTable_ShouldUseOracleQuotingAndIdentity()
    {
        var generator = new OracleTableGenerator(ConnectionString);

        var sql = generator.GenerateOracleTable<OracleProductBase>(ifNotExists: true);

        Assert.That(sql, Does.Contain("CREATE TABLE"));
        Assert.That(sql, Does.Contain("\"MS_ORACLE_PRODUCTS\""));
        Assert.That(sql, Does.Contain("\"Id\" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        Assert.That(sql, Does.Contain("\"Name\" VARCHAR2(100) NOT NULL"));
        Assert.That(sql, Does.Contain("\"CreatedAt\" TIMESTAMP DEFAULT SYSTIMESTAMP"));
        Assert.That(sql, Does.Not.Contain("IF NOT EXISTS"));

        var indexSql = generator.GenerateIndexSql<OracleProductBase>();
        Assert.That(indexSql.Single(), Is.EqualTo("CREATE INDEX \"idx_oracle_products_name\" ON \"MS_ORACLE_PRODUCTS\" (\"Name\");"));
    }

    [Test]
    public void AlterColumnTypeSql_ShouldUseOracleModifySyntax()
    {
        var sql = OracleProviderDescriptor.Create();
        var dialect = new UmbrellaFrame.ModelSync.Core.SqlGeneration.ModelSyncSqlDialect(sql);

        var alter = dialect.BuildAlterColumnTypeSql(string.Empty, TableName, "Amount", "NUMBER(12,2)");

        Assert.That(alter, Is.EqualTo("ALTER TABLE \"MS_ORACLE_PRODUCTS\" MODIFY \"Amount\" NUMBER(12,2);"));
    }

    [Test]
    [Category("Integration")]
    public void Oracle_Integration_ShouldCreateAndAlterTable()
    {
        Cleanup();

        var generator = new OracleTableGenerator(ConnectionString);
        generator.GenerateOracleTable<OracleProductBase>(ifNotExists: true);

        Assert.DoesNotThrow(() => generator.CreateTables());
        Assert.DoesNotThrow(() => generator.CreateTables());
        Assert.That(ColumnExists("Id"), Is.True);
        Assert.That(ColumnExists("Name"), Is.True);

        Assert.DoesNotThrow(() => generator.AddColumn<OracleProductWithStock>("Stock"));
        Assert.That(ColumnExists("Stock"), Is.True);

        Assert.DoesNotThrow(() => generator.RenameColumn<OracleProductWithStock>("Stock", "StockCount"));
        Assert.That(ColumnExists("StockCount"), Is.True);

        Assert.Throws<InvalidOperationException>(() => generator.DropColumn<OracleProductWithStock>("StockCount"));
        Assert.DoesNotThrow(() => generator.DropColumn<OracleProductWithStock>("StockCount", DestructiveOperationOptions.Allow()));
        Assert.That(ColumnExists("StockCount"), Is.False);

        Assert.Throws<InvalidOperationException>(() => generator.AlterColumnType<OracleProductWithStock>("Amount"));
        Assert.DoesNotThrow(() => generator.AlterColumnType<OracleProductWithStock>("Amount", DestructiveOperationOptions.Allow()));

        Assert.DoesNotThrow(() => generator.DropTables(DestructiveOperationOptions.Allow()));
        Assert.That(TableExists(), Is.False);
    }

    private static bool TableExists()
    {
        using var connection = new OracleConnection(ConnectionString);
        connection.Open();
        using var command = new OracleCommand("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :tableName", connection);
        command.Parameters.Add(new OracleParameter("tableName", TableName));
        return Convert.ToInt32(command.ExecuteScalar()) > 0;
    }

    private static bool ColumnExists(string column)
    {
        using var connection = new OracleConnection(ConnectionString);
        connection.Open();
        using var command = new OracleCommand("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = :tableName AND COLUMN_NAME = :columnName", connection);
        command.Parameters.Add(new OracleParameter("tableName", TableName));
        command.Parameters.Add(new OracleParameter("columnName", column));
        return Convert.ToInt32(command.ExecuteScalar()) > 0;
    }

    private static void Cleanup()
    {
        using var connection = new OracleConnection(ConnectionString);
        connection.Open();
        using var command = new OracleCommand(
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE \"MS_ORACLE_PRODUCTS\" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;",
            connection);
        command.ExecuteNonQuery();
    }

    [OracleTableName(TableName)]
    private sealed class OracleProductBase
    {
        [OracleColumnType(OracleColumnType.NUMBER, "10")]
        [OracleColumnPrimaryKey(isIdentity: true)]
        public int Id { get; set; }

        [OracleColumnType(OracleColumnType.VARCHAR2, "100")]
        [OracleColumnNotNull]
        [OracleColumnIndex("idx_oracle_products_name")]
        public string Name { get; set; } = string.Empty;

        [OracleColumnType(OracleColumnType.NUMBER, "12,2")]
        [OracleColumnDefault("0")]
        [OracleColumnCheck("\"Amount\" >= 0")]
        public decimal Amount { get; set; }

        [OracleColumnType(OracleColumnType.TIMESTAMP)]
        [OracleColumnDefault(OracleDefaultExpression.Systimestamp)]
        public DateTime CreatedAt { get; set; }
    }

    [OracleTableName(TableName)]
    private sealed class OracleProductWithStock
    {
        [OracleColumnType(OracleColumnType.NUMBER, "10")]
        [OracleColumnPrimaryKey(isIdentity: true)]
        public int Id { get; set; }

        [OracleColumnType(OracleColumnType.VARCHAR2, "100")]
        [OracleColumnNotNull]
        public string Name { get; set; } = string.Empty;

        [OracleColumnType(OracleColumnType.NUMBER, "12,2")]
        public decimal Amount { get; set; }

        [OracleColumnType(OracleColumnType.NUMBER, "10")]
        public int Stock { get; set; }
    }
}
