using UmbrellaFrame.ModelSync.Core.SqlGeneration;

namespace UmbrellaFrame.ModelSync.Oracle
{
    public static class OracleProviderDescriptor
    {
        public static ModelSyncProviderDescriptor Create()
            => new ModelSyncProviderDescriptor
            {
                ProviderId = "oracle",
                OpenQuote = "\"",
                CloseQuote = "\"",
                SupportsSchemas = true,
                IdentityKeyword = "GENERATED BY DEFAULT AS IDENTITY",
                AddColumnKeyword = "ADD",
                AlterColumnTypeStyle = AlterColumnTypeStyle.Modify,
                DefaultConstraintStyle = DefaultConstraintStyle.ModifyColumnDefault,
                HistoryStyle = HistorySqlStyle.OracleMerge,
                CatalogStyle = CatalogQueryStyle.OracleDataDictionary,
                RoutineCreationMode = RoutineCreationMode.CreateOrReplace,
                RoutineCatalogStyle = RoutineCatalogStyle.Unsupported,
                MigrationLockStyle = MigrationLockStyle.Unsupported,
                SystemDatabaseNames = new[] { "SYS", "SYSTEM", "XDB", "CTXSYS", "MDSYS", "ORDSYS" }
            };
    }
}
