using UmbrellaFrame.ModelSync.Core.SqlGeneration;

namespace UmbrellaFrame.ModelSync.PostgreSQL
{
    public static class PostgresProviderDescriptor
    {
        public static ModelSyncProviderDescriptor Create()
            => new ModelSyncProviderDescriptor
            {
                ProviderId = "postgresql",
                OpenQuote = "\"",
                CloseQuote = "\"",
                SupportsSchemas = true,
                IdentityKeyword = "GENERATED BY DEFAULT AS IDENTITY",
                AddColumnKeyword = "ADD COLUMN",
                AlterColumnTypeStyle = AlterColumnTypeStyle.AlterColumnType,
                DefaultConstraintStyle = DefaultConstraintStyle.AlterColumnSetDefault,
                HistoryStyle = HistorySqlStyle.ConflictUpdate,
                CatalogStyle = CatalogQueryStyle.ObjectRelationalCatalog,
                RoutineCreationMode = RoutineCreationMode.CreateOrReplace,
                RoutineCatalogStyle = RoutineCatalogStyle.FunctionCatalog,
                MigrationLockStyle = MigrationLockStyle.AdvisoryRoutine,
                SystemDatabaseNames = new[] { "postgres", "template0", "template1" }
            };
    }
}
